### ISSUE TITLE
Cluster Issuer Chart

### ISSUE THREAD

**Issue by JamesKirkAndSpock** [JamesKirkAndSpock/CommonHelmCharts#38]
Create a common chart for the Cluster Issuer.
- [x] Specify the  skeleton of a Cluster Issuer as per [here](https://docs.cert-manager.io/en/release-0.11/reference/clusterissuers.html) and [here](https://docs.cert-manager.io/en/release-0.11/reference/issuers.html)
```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: user@example.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          class: nginx
```
- [x] Ensure that the following are inserted as values and should be required
   - Cluster Issuer name.
```
   metadata:
     name: letsencrypt-prod
```
   - spec values.
```
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: user@example.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # An empty 'selector' means that this solver matches all domains
 ```
- [x] For the selectors accept a list with objects that should capture the YAML template values.
- [x]  Ensure the cluster issuer definition is a loop that can create many cluster-issuers. It should hence end with a `---` value.
